---
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "__REPLACE_WITH_ADMIN_HASH__"
  reserved: true
  backend_roles:
    - "admin"
  description: "Indexer admin user"

kibanaserver:
  hash: "__REPLACE_WITH_KIBANASERVER_HASH__"
  reserved: true
  description: "Dashboard service user"

wazuh-wui:
  hash: "__REPLACE_WITH_WAZUH_WUI_HASH__"
  reserved: false
  backend_roles:
    - "admin"
  description: "Wazuh dashboard API user"
